# Frontend Server Port
server.port=8080

# Backend API base URL — change this to the backend laptop's IP when deploying
backend.base-url=http://localhost:8081

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
